apiVersion: v1
kind: Service
metadata:
  name: employees-service
spec:
  selector:
    app: employees-app
  ports:
  - port: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-app
  labels:
    app: employees-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees-app
  template:
    metadata:
      labels:
        app: employees-app
    spec:
      containers:
        - name: golang-employees
          image: yohang/golang-employees:latest
          env:
            - name: DB_HOST
              value: "192.168.88.69"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "go_dev"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
